-- P2 ETL · 03 — Validação: contagem origem × destino para as 49 tabelas
-- (a validação do merge das híbridas está no próprio 02-merge-main.sql)
-- alembic_version fica FORA da contagem: é reportada à parte (versão origem × destino),
-- porque o destino pode legitimamente estar à frente (migrations do Intelligence).
CREATE TEMP TABLE r(item text, origem bigint, destino bigint, ok text);
INSERT INTO r SELECT 'chief_perfil_perguntas', (SELECT count(*) FROM intel_src.chief_perfil_perguntas), (SELECT count(*) FROM intelligence.chief_perfil_perguntas), CASE WHEN (SELECT count(*) FROM intel_src.chief_perfil_perguntas) = (SELECT count(*) FROM intelligence.chief_perfil_perguntas) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'allocation_history', (SELECT count(*) FROM intel_src.allocation_history), (SELECT count(*) FROM intelligence.allocation_history), CASE WHEN (SELECT count(*) FROM intel_src.allocation_history) = (SELECT count(*) FROM intelligence.allocation_history) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'allocation_history_shortlist', (SELECT count(*) FROM intel_src.allocation_history_shortlist), (SELECT count(*) FROM intelligence.allocation_history_shortlist), CASE WHEN (SELECT count(*) FROM intel_src.allocation_history_shortlist) = (SELECT count(*) FROM intelligence.allocation_history_shortlist) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'attractiveness_snapshots', (SELECT count(*) FROM intel_src.attractiveness_snapshots), (SELECT count(*) FROM intelligence.attractiveness_snapshots), CASE WHEN (SELECT count(*) FROM intel_src.attractiveness_snapshots) = (SELECT count(*) FROM intelligence.attractiveness_snapshots) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'backtest_jobs', (SELECT count(*) FROM intel_src.backtest_jobs), (SELECT count(*) FROM intelligence.backtest_jobs), CASE WHEN (SELECT count(*) FROM intel_src.backtest_jobs) = (SELECT count(*) FROM intelligence.backtest_jobs) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'benchmark_market_cache', (SELECT count(*) FROM intel_src.benchmark_market_cache), (SELECT count(*) FROM intelligence.benchmark_market_cache), CASE WHEN (SELECT count(*) FROM intel_src.benchmark_market_cache) = (SELECT count(*) FROM intelligence.benchmark_market_cache) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'benchmark_qa', (SELECT count(*) FROM intel_src.benchmark_qa), (SELECT count(*) FROM intelligence.benchmark_qa), CASE WHEN (SELECT count(*) FROM intel_src.benchmark_qa) = (SELECT count(*) FROM intelligence.benchmark_qa) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_career_history', (SELECT count(*) FROM intel_src.chief_career_history), (SELECT count(*) FROM intelligence.chief_career_history), CASE WHEN (SELECT count(*) FROM intel_src.chief_career_history) = (SELECT count(*) FROM intelligence.chief_career_history) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_contextual_qa', (SELECT count(*) FROM intel_src.chief_contextual_qa), (SELECT count(*) FROM intelligence.chief_contextual_qa), CASE WHEN (SELECT count(*) FROM intel_src.chief_contextual_qa) = (SELECT count(*) FROM intelligence.chief_contextual_qa) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_enrichment_history', (SELECT count(*) FROM intel_src.chief_enrichment_history), (SELECT count(*) FROM intelligence.chief_enrichment_history), CASE WHEN (SELECT count(*) FROM intel_src.chief_enrichment_history) = (SELECT count(*) FROM intelligence.chief_enrichment_history) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_improvement_event', (SELECT count(*) FROM intel_src.chief_improvement_event), (SELECT count(*) FROM intelligence.chief_improvement_event), CASE WHEN (SELECT count(*) FROM intel_src.chief_improvement_event) = (SELECT count(*) FROM intelligence.chief_improvement_event) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_laudo', (SELECT count(*) FROM intel_src.chief_laudo), (SELECT count(*) FROM intelligence.chief_laudo), CASE WHEN (SELECT count(*) FROM intel_src.chief_laudo) = (SELECT count(*) FROM intelligence.chief_laudo) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_laudo_modal_state', (SELECT count(*) FROM intel_src.chief_laudo_modal_state), (SELECT count(*) FROM intelligence.chief_laudo_modal_state), CASE WHEN (SELECT count(*) FROM intel_src.chief_laudo_modal_state) = (SELECT count(*) FROM intelligence.chief_laudo_modal_state) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_platform_history', (SELECT count(*) FROM intel_src.chief_platform_history), (SELECT count(*) FROM intelligence.chief_platform_history), CASE WHEN (SELECT count(*) FROM intel_src.chief_platform_history) = (SELECT count(*) FROM intelligence.chief_platform_history) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_rerank_cache', (SELECT count(*) FROM intel_src.chief_rerank_cache), (SELECT count(*) FROM intelligence.chief_rerank_cache), CASE WHEN (SELECT count(*) FROM intel_src.chief_rerank_cache) = (SELECT count(*) FROM intelligence.chief_rerank_cache) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_reverse_matches', (SELECT count(*) FROM intel_src.chief_reverse_matches), (SELECT count(*) FROM intelligence.chief_reverse_matches), CASE WHEN (SELECT count(*) FROM intel_src.chief_reverse_matches) = (SELECT count(*) FROM intelligence.chief_reverse_matches) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_reverse_profile', (SELECT count(*) FROM intel_src.chief_reverse_profile), (SELECT count(*) FROM intelligence.chief_reverse_profile), CASE WHEN (SELECT count(*) FROM intel_src.chief_reverse_profile) = (SELECT count(*) FROM intelligence.chief_reverse_profile) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_snapshot_before_op', (SELECT count(*) FROM intel_src.chief_snapshot_before_op), (SELECT count(*) FROM intelligence.chief_snapshot_before_op), CASE WHEN (SELECT count(*) FROM intel_src.chief_snapshot_before_op) = (SELECT count(*) FROM intelligence.chief_snapshot_before_op) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_stimulus_event', (SELECT count(*) FROM intel_src.chief_stimulus_event), (SELECT count(*) FROM intelligence.chief_stimulus_event), CASE WHEN (SELECT count(*) FROM intel_src.chief_stimulus_event) = (SELECT count(*) FROM intelligence.chief_stimulus_event) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'deal_enrichment_jobs', (SELECT count(*) FROM intel_src.deal_enrichment_jobs), (SELECT count(*) FROM intelligence.deal_enrichment_jobs), CASE WHEN (SELECT count(*) FROM intel_src.deal_enrichment_jobs) = (SELECT count(*) FROM intelligence.deal_enrichment_jobs) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'deal_enrichments', (SELECT count(*) FROM intel_src.deal_enrichments), (SELECT count(*) FROM intelligence.deal_enrichments), CASE WHEN (SELECT count(*) FROM intel_src.deal_enrichments) = (SELECT count(*) FROM intelligence.deal_enrichments) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'deal_sales_ops', (SELECT count(*) FROM intel_src.deal_sales_ops), (SELECT count(*) FROM intelligence.deal_sales_ops), CASE WHEN (SELECT count(*) FROM intel_src.deal_sales_ops) = (SELECT count(*) FROM intelligence.deal_sales_ops) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'governance_conflicts', (SELECT count(*) FROM intel_src.governance_conflicts), (SELECT count(*) FROM intelligence.governance_conflicts), CASE WHEN (SELECT count(*) FROM intel_src.governance_conflicts) = (SELECT count(*) FROM intelligence.governance_conflicts) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'ingestion_logs', (SELECT count(*) FROM intel_src.ingestion_logs), (SELECT count(*) FROM intelligence.ingestion_logs), CASE WHEN (SELECT count(*) FROM intel_src.ingestion_logs) = (SELECT count(*) FROM intelligence.ingestion_logs) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'iqp_snapshots', (SELECT count(*) FROM intel_src.iqp_snapshots), (SELECT count(*) FROM intelligence.iqp_snapshots), CASE WHEN (SELECT count(*) FROM intel_src.iqp_snapshots) = (SELECT count(*) FROM intelligence.iqp_snapshots) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_chief_alerts', (SELECT count(*) FROM intel_src.jd_chief_alerts), (SELECT count(*) FROM intelligence.jd_chief_alerts), CASE WHEN (SELECT count(*) FROM intel_src.jd_chief_alerts) = (SELECT count(*) FROM intelligence.jd_chief_alerts) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_chief_match_comments', (SELECT count(*) FROM intel_src.jd_chief_match_comments), (SELECT count(*) FROM intelligence.jd_chief_match_comments), CASE WHEN (SELECT count(*) FROM intel_src.jd_chief_match_comments) = (SELECT count(*) FROM intelligence.jd_chief_match_comments) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_chief_stages', (SELECT count(*) FROM intel_src.jd_chief_stages), (SELECT count(*) FROM intelligence.jd_chief_stages), CASE WHEN (SELECT count(*) FROM intel_src.jd_chief_stages) = (SELECT count(*) FROM intelligence.jd_chief_stages) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_list_quality', (SELECT count(*) FROM intel_src.jd_list_quality), (SELECT count(*) FROM intelligence.jd_list_quality), CASE WHEN (SELECT count(*) FROM intel_src.jd_list_quality) = (SELECT count(*) FROM intelligence.jd_list_quality) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'mcp_query_log', (SELECT count(*) FROM intel_src.mcp_query_log), (SELECT count(*) FROM intelligence.mcp_query_log), CASE WHEN (SELECT count(*) FROM intel_src.mcp_query_log) = (SELECT count(*) FROM intelligence.mcp_query_log) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'mql_candidates', (SELECT count(*) FROM intel_src.mql_candidates), (SELECT count(*) FROM intelligence.mql_candidates), CASE WHEN (SELECT count(*) FROM intel_src.mql_candidates) = (SELECT count(*) FROM intelligence.mql_candidates) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'novo_funil_pipedrive', (SELECT count(*) FROM intel_src.novo_funil_pipedrive), (SELECT count(*) FROM intelligence.novo_funil_pipedrive), CASE WHEN (SELECT count(*) FROM intel_src.novo_funil_pipedrive) = (SELECT count(*) FROM intelligence.novo_funil_pipedrive) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'pipedrive_write_log', (SELECT count(*) FROM intel_src.pipedrive_write_log), (SELECT count(*) FROM intelligence.pipedrive_write_log), CASE WHEN (SELECT count(*) FROM intel_src.pipedrive_write_log) = (SELECT count(*) FROM intelligence.pipedrive_write_log) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'pipeline_runs', (SELECT count(*) FROM intel_src.pipeline_runs), (SELECT count(*) FROM intelligence.pipeline_runs), CASE WHEN (SELECT count(*) FROM intel_src.pipeline_runs) = (SELECT count(*) FROM intelligence.pipeline_runs) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'platform_sync_state', (SELECT count(*) FROM intel_src.platform_sync_state), (SELECT count(*) FROM intelligence.platform_sync_state), CASE WHEN (SELECT count(*) FROM intel_src.platform_sync_state) = (SELECT count(*) FROM intelligence.platform_sync_state) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'system_prompts', (SELECT count(*) FROM intel_src.system_prompts), (SELECT count(*) FROM intelligence.system_prompts), CASE WHEN (SELECT count(*) FROM intel_src.system_prompts) = (SELECT count(*) FROM intelligence.system_prompts) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'ui_access_grant', (SELECT count(*) FROM intel_src.ui_access_grant), (SELECT count(*) FROM intelligence.ui_access_grant), CASE WHEN (SELECT count(*) FROM intel_src.ui_access_grant) = (SELECT count(*) FROM intelligence.ui_access_grant) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'uploaded_files', (SELECT count(*) FROM intel_src.uploaded_files), (SELECT count(*) FROM intelligence.uploaded_files), CASE WHEN (SELECT count(*) FROM intel_src.uploaded_files) = (SELECT count(*) FROM intelligence.uploaded_files) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'user_activity_log', (SELECT count(*) FROM intel_src.user_activity_log), (SELECT count(*) FROM intelligence.user_activity_log), CASE WHEN (SELECT count(*) FROM intel_src.user_activity_log) = (SELECT count(*) FROM intelligence.user_activity_log) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'user_favorites', (SELECT count(*) FROM intel_src.user_favorites), (SELECT count(*) FROM intelligence.user_favorites), CASE WHEN (SELECT count(*) FROM intel_src.user_favorites) = (SELECT count(*) FROM intelligence.user_favorites) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'users', (SELECT count(*) FROM intel_src.users), (SELECT count(*) FROM intelligence.users), CASE WHEN (SELECT count(*) FROM intel_src.users) = (SELECT count(*) FROM intelligence.users) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_embeddings', (SELECT count(*) FROM intel_src.chief_embeddings), (SELECT count(*) FROM intelligence.chief_embeddings), CASE WHEN (SELECT count(*) FROM intel_src.chief_embeddings) = (SELECT count(*) FROM intelligence.chief_embeddings) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'chief_field_history', (SELECT count(*) FROM intel_src.chief_field_history), (SELECT count(*) FROM intelligence.chief_field_history), CASE WHEN (SELECT count(*) FROM intel_src.chief_field_history) = (SELECT count(*) FROM intelligence.chief_field_history) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'job_descriptions', (SELECT count(*) FROM intel_src.job_descriptions), (SELECT count(*) FROM intelligence.job_descriptions), CASE WHEN (SELECT count(*) FROM intel_src.job_descriptions) = (SELECT count(*) FROM intelligence.job_descriptions) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'job_embeddings', (SELECT count(*) FROM intel_src.job_embeddings), (SELECT count(*) FROM intelligence.job_embeddings), CASE WHEN (SELECT count(*) FROM intel_src.job_embeddings) = (SELECT count(*) FROM intelligence.job_embeddings) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_briefing_embeddings', (SELECT count(*) FROM intel_src.jd_briefing_embeddings), (SELECT count(*) FROM intelligence.jd_briefing_embeddings), CASE WHEN (SELECT count(*) FROM intel_src.jd_briefing_embeddings) = (SELECT count(*) FROM intelligence.jd_briefing_embeddings) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_extracted_metadata', (SELECT count(*) FROM intel_src.jd_extracted_metadata), (SELECT count(*) FROM intelligence.jd_extracted_metadata), CASE WHEN (SELECT count(*) FROM intel_src.jd_extracted_metadata) = (SELECT count(*) FROM intelligence.jd_extracted_metadata) THEN 'OK' ELSE 'DIVERGE' END;
INSERT INTO r SELECT 'jd_results', (SELECT count(*) FROM intel_src.jd_results), (SELECT count(*) FROM intelligence.jd_results), CASE WHEN (SELECT count(*) FROM intel_src.jd_results) = (SELECT count(*) FROM intelligence.jd_results) THEN 'OK' ELSE 'DIVERGE' END;
SELECT * FROM r ORDER BY (ok='DIVERGE') DESC, item;
SELECT 'alembic_version' AS item,
       (SELECT string_agg(version_num, ',') FROM intel_src.alembic_version)    AS origem,
       (SELECT string_agg(version_num, ',') FROM intelligence.alembic_version) AS destino,
       CASE WHEN (SELECT string_agg(version_num, ',') FROM intel_src.alembic_version)
               = (SELECT string_agg(version_num, ',') FROM intelligence.alembic_version)
            THEN 'OK' ELSE 'INFO: destino gerido pelo Alembic do Intelligence (não é divergência de dados)' END AS ok;
SELECT CASE WHEN EXISTS (SELECT 1 FROM r WHERE ok='DIVERGE') THEN 'RESULTADO: HÁ DIVERGÊNCIAS'
            ELSE 'RESULTADO: ZERO DIVERGÊNCIAS — '||(SELECT count(*) FROM r)||'/'||(SELECT count(*) FROM r)||' TABELAS OK' END;
